<a href="https://colab.research.google.com/github/HongTorxh/Study_Paran/blob/main/tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import tensorflow as tf

In [35]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [36]:
tf.constant(((1,2,3), (4,5,6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [38]:
arr = np.array([1,2,3])

In [40]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [41]:
tensor.shape

TensorShape([3])

In [43]:
tensor.dtype

tf.int64

In [47]:
tf.constant([1,2,3], dtype = tf.uint8)
tensor = tf.constant([1,2,3], dtype = tf.float32)

In [48]:
arr = np.array([1,2,3], dtype = np.float32)

In [49]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [50]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [51]:
tf.cast(tensor, dtype = tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [52]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [53]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

In [54]:
type(tensor.numpy())

numpy.ndarray

In [55]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [56]:
np.random.randn(9)

array([-1.11101528, -1.03403747, -1.66178468, -2.20941518, -1.9391849 ,
        0.33014251,  1.21137368,  1.13395003, -0.71000531])

In [57]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0316188 ,  0.9732385 ,  0.16103193],
       [ 0.30138138, -0.70843625, -0.32681575],
       [ 1.418125  , -1.5122777 , -0.5324891 ]], dtype=float32)>

In [58]:
tf.random.uniform([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.24453735, 0.33639693, 0.11610305, 0.72867537],
       [0.32365096, 0.14763057, 0.75285506, 0.75747824],
       [0.23713648, 0.84769094, 0.11027443, 0.24370694],
       [0.2670622 , 0.42453432, 0.3368616 , 0.09413409]], dtype=float32)>